#!/usr/bin/env bash
#The script that displays the content of the file /etc/passwd.
passwd_file="/etc/passwd"
if [ ! -f "$passwd_file" ]; then
    echo "Error: /etc/passwd file not found."
    exit 1
fi
while IFS=":" read -r username uid homedir; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $homedir"
done < "$passwd_file"

