#!/usr/bin/env bash
# This script is displaying "Best School" 8 times, goodluck and badluck.
iterations=10
counter=0
while [ $counter -lt $iterations ]
do
	if [ $counter -eq 3 ];then
		echo "bad luck"
	elif [ $counter -eq 7 ];then
		echo "good luck"
	else
		echo "Best School"
	fi
		((counter++))
done
