#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
max_hours=12
max_minutes=59
hours=0
minutes=1
while [ $hours -le $max_hours ]
do
    echo "Hour: $hours"
    while [ $minutes -le $max_minutes ]
    do
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
    minutes=1
done
